language: node_js
node_js:
  - 0.8
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libopenobex1-dev libobexftp0-dev bluetooth libpam0g-dev libcairo2-dev libjpeg8-dev libgif-dev libavahi-compat-libdnssd-dev libgnome-keyring-dev g++ libssl-dev 
